### ISSUE TITLE
Apparent corrupted foundation CSS file

### ISSUE THREAD

**Issue by deekayen** [eucalyptuss/material-foundation#22]
The latest commit of the compiled CSS appears to be just a error backtrace instead of well formed CSS:

https://github.com/eucalyptuss/material-foundation/blob/a3b69152de4b7e1def6c04f178b6954dfe60dadf/css/material-foundation.css

**Comment by eucalyptuss** [comment]
The latest version is a master branch.

**Comment by eucalyptuss** [comment]
fixed
