### ISSUE TITLE
Enable Flex

### ISSUE THREAD

**Issue by Ballpin** [eucalyptuss/material-foundation#33]
Hello,

Getting this error when turning flex on. 

Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
        on line 80 of bower_components/foundation-sites/scss/components/_top-bar.scss
        from line 36 of scss/material-foundation.scss
  Use --trace for backtrace.
Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
        on line 80 of bower_components/foundation-sites/scss/components/_top-bar.scss
        from line 36 of scss/material-foundation.scss
        from line 2 of scss/demo.scss
  Use --trace for backtrace.

Suggestions?

**Comment by DanielRuf** [comment]
This sounds like an issue with the Sass compiler or the used Foundation version.

**Comment by Ballpin** [comment]
Now this was a while ago but if i remember right. It happen when i did a a clean install by following your instructions in the Readme. The only thing i did as extra was removing the "//" on flex lines that you are suppose to do according to Foundation. Then comment out the default grid.

Im not sure if you want me to leave this open. But for my part i have moved to UIKit, i like their framework way more then Foundation actually. 

But i do appreciate the work you have put into this project, im sure it will help other people once it has been fixed, :-)

**Comment by DanielRuf** [comment]
I'll try to reproduce this and provide a PR with a fix.

**Comment by eucalyptuss** [comment]
flex is now working fine in v0.2.0
