### ISSUE TITLE
Import from another package

### ISSUE THREAD

**Issue by prem-prakash** [eucalyptuss/material-foundation#34]
This import is relative to another package, it does not work if bower directory is other than default, which is my case in some projects.

```scss
@import '../bower_components/foundation-sites/scss/util/util';
```

**Comment by matvinculado** [comment]
try this:

for those line with errors remove: **../bower_components/** and replace it with **../../**

hope it helpts

**Comment by eucalyptuss** [comment]
As SASS doesn't allow variables in imports in this case you need to update the path manually.
