### ISSUE TITLE
Replace material-design-iconic-font

### ISSUE THREAD

**Issue by DanielRuf** [eucalyptuss/material-foundation#44]
material-design-iconic-font is not actively maintained.

https://github.com/Templarian/MaterialDesign combined with the original font by Google should be much better.

Icons should be part of a separate repository. At the moment the MaterialDesign repository is the biggest one by the community and should be preferred.

Describe how people can include the official Google Material Icons and the linked repository.

**Comment by eucalyptuss** [comment]
replaced with an official implementation in v0.2.0
