### ISSUE TITLE
Hi eucalyptuss - "Fatal error: Unable to find Gruntfile"

### ISSUE THREAD

**Issue by el-besto** [eucalyptuss/material-foundation#5]
I was hoping to take a look at the repo as I have a class project that I am working on and wanted to use this repo as a basis and extend with custom styles and functionality. After cloning I attempted to run Grunt and was presented with the error:  "Fatal error: Unable to find Gruntfile".

Then I realized that there is no grunt file in the root. I have codekit and tried importing the project in there since you have the codekit config file in there, but I also had errors doing that... Haha

Could you upload your gruntfile so that I can see the project in action?

Thanks,

Angelo

**Comment by eucalyptuss** [comment]
Hi,
I stopped developing it while ago, and yes, grunt is not there, this is a very work in progress I would say. The only way you can run it is codekit, it's strange it's returning errors. Are you using Codekit 2, or the old one?
Anyway I can't much help you with this at the moment. But if you find some solution please let me know
Mikolaj

**Comment by el-besto** [comment]
Ok cool thanks for the feedback. I can take a wack and see if I can help. Ill fork to our project repo and if we find a solution submit a pull request. I am using CodeKit 2 but havent used a config file before. Im more familiar with Grunt so Ill try to get that setup. 

Cheers,

Angelo
