### ISSUE TITLE
Broken relative import statements in scss files

### ISSUE THREAD

**Issue by michaelvolz** [eucalyptuss/material-foundation#51]
At the moment there are import statements like:

`@import "../../node_modules/material-design-iconic-font/scss/material-design-iconic-font.scss";`

in "material-foundation/scss/style/**_icons.scss**" and other files which point to a non existing node_modules folder.

Please remove the relative module paths either by
a) using **Webpack** and changing all imports to "~node_modules/..."
or
b) using a "**Tilde**" **plugin** for Sass/Grunt/Gulp and also changing all imports to "~node_modules/..."

I like your material-foundation very much.

**Comment by eucalyptuss** [comment]
Moved to the official of material design icons in v0.2.0
