### ISSUE TITLE
Ripple effect makes links not working

### ISSUE THREAD

**Issue by corneboele** [eucalyptuss/material-foundation#52]
If I enable the ripple js, there is a nice ripple effect on links (`<a>`) that have `.button` class. But the links do not work anymore.

After commenting out the following in ripple.js, the links are working and ripple effect stays.

`event.preventDefault();`

The reason for this line is probably to prevent the scroll to top on links/buttons that do not point to an address? Maybe we can check for `a href="[not #]"` or something?

**Comment by eucalyptuss** [comment]
Damn it, sorry for that. Will take care of it soon
